# Generated by Django 5.2.3 on 2025-06-17 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_container'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cost_of_product',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Base cost of the product excluding selling costs.', max_digits=10, verbose_name='cost of product'),
        ),
        migrations.AddField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='cost price'),
        ),
        migrations.AddField(
            model_name='product',
            name='selling_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Cost associated with selling this product, e.g., shipping, handling.', max_digits=10, verbose_name='selling cost'),
        ),
        migrations.AddField(
            model_name='product',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='selling price'),
        ),
    ]
