# Generated by Django 5.2.3 on 2025-06-17 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_product_cost_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.IntegerField(default=0, max_length=100, verbose_name='SKU (Stock Keeping Unit)'),
        ),
    ]
