# Generated by Django 5.2.3 on 2025-06-17 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.IntegerField(default=0, verbose_name='SKU (Stock Keeping Unit)'),
        ),
    ]
