# Generated by Django 5.2.3 on 2025-06-17 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_product_options_remove_product_sku_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producttransferlog',
            old_name='quantity',
            new_name='quantity_transferred',
        ),
        migrations.RemoveField(
            model_name='producttransferlog',
            name='notes',
        ),
        migrations.AddField(
            model_name='producttransferlog',
            name='description',
            field=models.TextField(blank=True, verbose_name='description/notes'),
        ),
    ]
