# Generated by Django 5.2.1 on 2025-05-30 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_id_code', models.CharField(help_text='e.g., MSKU1234567', max_length=50, unique=True)),
                ('type', models.CharField(help_text='e.g., 20ft Dry, 40ft HC Reefer', max_length=50)),
                ('status', models.CharField(choices=[('EM', 'Empty'), ('LO', 'Loading'), ('LD', 'Loaded'), ('IT', 'In Transit'), ('AD', 'At Destination'), ('UL', 'Unloading')], default='EM', max_length=2)),
                ('current_location_description', models.CharField(blank=True, help_text='e.g., Warehouse A, Port of LA', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
