# Generated by Django 5.2.1 on 2025-06-15 04:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('containers', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_tracking_id', models.CharField(blank=True, max_length=100, unique=True, verbose_name='shipment tracking ID')),
                ('destination_address', models.TextField(verbose_name='destination address')),
                ('status', models.CharField(choices=[('PC', 'Pending Confirmation'), ('PR', 'Processing'), ('AP', 'Awaiting Pickup'), ('SH', 'Shipped'), ('IT', 'In Transit'), ('AH', 'Arrived at Hub/Port'), ('CC', 'Customs Clearance'), ('OD', 'Out for Local Delivery'), ('DE', 'Delivered'), ('DL', 'Delayed'), ('CA', 'Cancelled'), ('PD', 'Partially Delivered')], default='PC', max_length=2, verbose_name='status')),
                ('estimated_departure_date', models.DateTimeField(blank=True, null=True, verbose_name='estimated departure date')),
                ('actual_departure_date', models.DateTimeField(blank=True, null=True, verbose_name='actual departure date')),
                ('estimated_delivery_date', models.DateTimeField(blank=True, null=True, verbose_name='estimated delivery date')),
                ('actual_delivery_date', models.DateTimeField(blank=True, null=True, verbose_name='actual delivery date')),
                ('notes', models.TextField(blank=True, verbose_name='internal notes')),
                ('customer_notes', models.TextField(blank=True, verbose_name='notes for customer')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('container', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipment', to='containers.container', verbose_name='container')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shipments', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('customer', models.ForeignKey(limit_choices_to={'role': 'CU'}, on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to=settings.AUTH_USER_MODEL, verbose_name='customer')),
                ('origin_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments_originated', to='inventory.warehouse', verbose_name='origin warehouse')),
            ],
            options={
                'verbose_name': 'shipment',
                'verbose_name_plural': 'shipments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='quantity')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipment_items', to='inventory.product', verbose_name='product')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shipments.shipment', verbose_name='shipment')),
            ],
            options={
                'verbose_name': 'shipment item',
                'verbose_name_plural': 'shipment items',
                'unique_together': {('shipment', 'product')},
            },
        ),
    ]
