# Generated by Django 5.2.1 on 2025-06-15 04:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_id_code', models.CharField(help_text='e.g., MSKU1234567, a unique identifier for the container', max_length=50, unique=True, verbose_name='container ID code')),
                ('type', models.CharField(help_text='e.g., 20ft Dry, 40ft HC Reefer, 20ft Tank', max_length=50, verbose_name='container type')),
                ('status', models.CharField(choices=[('EM', 'Empty'), ('AV', 'Available'), ('LO', 'Loading'), ('LD', 'Loaded'), ('TP', 'In Transit to Port/Hub'), ('AP', 'At Port/Hub of Origin'), ('IT', 'In Transit (Main Leg)'), ('AD', 'At Port/Hub of Destination'), ('TC', 'In Transit to Customer'), ('UL', 'Unloading at Customer'), ('AR', 'Awaiting Return'), ('TR', 'In Transit (Return)'), ('MA', 'Under Maintenance'), ('DA', 'Damaged'), ('DE', 'Decommissioned')], default='AV', max_length=2, verbose_name='status')),
                ('current_location_description', models.CharField(blank=True, help_text='e.g., Warehouse A, Port of LA, On Vessel Evergreen', max_length=255, verbose_name='current location description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('assigned_customer', models.ForeignKey(blank=True, limit_choices_to={'role': 'CU'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_containers', to=settings.AUTH_USER_MODEL, verbose_name='assigned customer')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_containers', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('current_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='containers_at_warehouse', to='inventory.warehouse', verbose_name='current warehouse')),
            ],
            options={
                'verbose_name': 'container',
                'verbose_name_plural': 'containers',
                'ordering': ['container_id_code'],
            },
        ),
    ]
