# Generated by Django 5.2.1 on 2025-05-30 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deliveries', '0001_initial'),
        ('shipments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverytask',
            name='dispatcher',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'DI'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='shipment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_task', to='shipments.shipment'),
        ),
    ]
