# Generated by Django 5.2.1 on 2025-06-15 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerCodeSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Container Code Sequence',
            },
        ),
        migrations.RemoveField(
            model_name='container',
            name='assigned_customer',
        ),
        migrations.AlterField(
            model_name='container',
            name='container_id_code',
            field=models.CharField(blank=True, help_text='e.g., MSKU1234567, a unique identifier for the container', max_length=50, unique=True, verbose_name='container ID code'),
        ),
        migrations.AlterField(
            model_name='container',
            name='type',
            field=models.CharField(help_text='e.g., Goods Container, Refrigerated Container, Tank Container, etc.', max_length=50, verbose_name='container type'),
        ),
    ]
