# Generated by Django 5.2.1 on 2025-06-15 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0002_containercodesequence_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='container',
            options={'ordering': ['-updated_at', 'container_id_code'], 'verbose_name': 'container', 'verbose_name_plural': 'containers'},
        ),
        migrations.AlterModelOptions(
            name='containercodesequence',
            options={'verbose_name': 'Container Code Sequence', 'verbose_name_plural': 'Container Code Sequences'},
        ),
        migrations.RenameField(
            model_name='containercodesequence',
            old_name='current',
            new_name='current_number',
        ),
        migrations.AddField(
            model_name='container',
            name='current_goods_description',
            field=models.TextField(blank=True, help_text='Brief description of goods currently or last loaded, if tracked directly on container.', verbose_name='current goods description'),
        ),
        migrations.AddField(
            model_name='container',
            name='last_known_origin',
            field=models.CharField(blank=True, help_text='Origin port/city of its last significant journey, if tracked directly.', max_length=255, verbose_name='last known origin'),
        ),
        migrations.AlterField(
            model_name='container',
            name='container_id_code',
            field=models.CharField(blank=True, help_text='e.g., #C-00001', max_length=50, unique=True, verbose_name='container ID code'),
        ),
        migrations.AlterField(
            model_name='container',
            name='current_location_description',
            field=models.CharField(blank=True, help_text="Free text for current location, e.g., 'Port of LA, Berth 5'", max_length=255, verbose_name='current location description'),
        ),
        migrations.AlterField(
            model_name='container',
            name='status',
            field=models.CharField(choices=[('EM', 'Empty'), ('AV', 'Available'), ('LO', 'Loading'), ('LD', 'Loaded'), ('TP', 'In Transit to Port/Hub'), ('AP', 'At Port/Hub of Origin'), ('IT', 'In Transit (Main Leg)'), ('AD', 'At Port/Hub of Destination'), ('TC', 'In Transit to Customer/Warehouse'), ('UL', 'Unloading'), ('AR', 'Awaiting Return'), ('TR', 'In Transit (Return)'), ('MA', 'Under Maintenance'), ('DA', 'Damaged'), ('DE', 'Decommissioned')], default='AV', max_length=2, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='container',
            name='type',
            field=models.CharField(help_text='e.g., 20ft Dry Standard, 40ft High Cube, Reefer', max_length=100, verbose_name='container type'),
        ),
    ]
