# Generated by Django 5.2.3 on 2025-06-17 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0003_alter_container_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='bank_charges',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Bank charges of the container.', max_digits=10, null=True, verbose_name='bank charges'),
        ),
        migrations.AddField(
            model_name='container',
            name='discharge',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='discharge of the container.', max_digits=10, null=True, verbose_name='discharges'),
        ),
        migrations.AddField(
            model_name='container',
            name='duty_and_ag_fess',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='duty and AG fees of the container.', max_digits=10, null=True, verbose_name='duty and AG fees'),
        ),
        migrations.AddField(
            model_name='container',
            name='transportation_fees',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Transport of the container.', max_digits=10, null=True, verbose_name='Transportation fees'),
        ),
    ]
