# Generated by Django 5.2.1 on 2025-06-15 04:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='title')),
                ('message', models.TextField(verbose_name='message')),
                ('channel', models.CharField(choices=[('EM', 'Email'), ('PU', 'Push Notification'), ('IA', 'In-App Message')], default='EM', max_length=2, verbose_name='channel')),
                ('status', models.CharField(choices=[('PE', 'Pending'), ('SE', 'Sent'), ('FA', 'Failed'), ('RD', 'Read'), ('AR', 'Archived')], default='PE', max_length=2, verbose_name='status')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='object ID')),
                ('action_url', models.URLField(blank=True, null=True, verbose_name='action URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='sent at')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='read at')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='content type')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='recipient')),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
